sudo: false
language: scala
cache:
  directories:
    - '$HOME/.ivy2/cache'
scala:
- 2.11.6
jdk:
- openjdk8
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
branches:
  except:
    - master
